### ISSUE TITLE
Nonstop import

### ISSUE THREAD

**Issue by rex2630** [RenewedPlains/codeswholesale-woocommerce-patch#2]
Products  are importing after deleting script, i dont know how to disable it :/

**Comment by RenewedPlains** [comment]
If you have deleted the script, the import batch cannot continue because it cannot find the reference. Try to delete the files of my plugin on your FTP under /wp-content/plugins/. 

Alternatively restart your PHP service.

**Comment by rex2630** [comment]
Its problem of original codeswholesale plugin, not this one.
