### ISSUE TITLE
Import stuck

### ISSUE THREAD

**Issue by officialmmt** [RenewedPlains/codeswholesale-woocommerce-patch#3]
I trying to import products. It is stuck in 1279 and can not start again.

**Comment by officialmmt** [comment]
I testing dev branch. It seems like stuck at one worker. Screenshot link below. I hope it help you while dev.
https://prnt.sc/uu802e

**Comment by officialmmt** [comment]
Second ss. Only one worker works and around 3127. But processed product count is 1702.
https://prnt.sc/uu8vnp

**Comment by RenewedPlains** [comment]
Should be fixed with the newest version 0.9.5. :) Try it and let me know how it worked or if there are still problems.
