### ISSUE TITLE
Logout / or not available after settings save

### ISSUE THREAD

**Issue by pjindras** [RenewedPlains/codeswholesale-woocommerce-patch#4]
Hello, my plugin was working well, but after hosting and db migration, when i try to save my settings, it sign me out or make not available error, how can i compleatly remove bojett in my db to install it clear again? Or what to do? THX

**Comment by RenewedPlains** [comment]
Just deactivate the Plugin. This will remove all DB Tables from Bojett Plugin and gives you a new Try :)
